apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80 # Le port que vous utilisez pour acc√©der au service
      targetPort: 5000 # Le port du conteneur
  type: LoadBalancer # Ou NodePort si vous utilisez Minikube
